[simulation]
max_frequency = 1e9             # [Hz] maximium frequency to resolve
voxels_per_min_wavelength = 50  # [] number of voxels per minimum wavelength
voxels_per_min_feature = 4      # [] number of voxels per minimum feature size

[geometry]
x_len = 1.0                     # [m] length of waveguide in x-direction
y_len = 1.0                     # [m] length of waveguide in y-direction
z_len = 1.0                     # [m] length of waveguide in z-direction (direction of propogation)
ep_r = 1                        # [] diagonally isotropic relative permetivity inside waveguide 
mu_r = 1                        # [] diagonally isotropic relative permeability inside waveguide